//You are given two strings s and t.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Return the letter that was added to t.

using System.Collections.Generic;
using System;

public class Solution
{
    public char FindTheDifference(string s, string t)
    {
        Dictionary<char, int> count = new Dictionary<char, int>();

        foreach (char c in s)
        {
            if (count.ContainsKey(c))
            {
                count[c]++;
            }
            else
            {
                count[c] = 1;
            }
        }

        foreach (char c in t)
        {
            if (count.ContainsKey(c) && count[c] > 0)
            {
                count[c]--;
            }
            else
            {
                return c;
            }
        }

        throw new ArgumentException("Invalid input strings");
    }
}
